version: "3.4"
services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    hostname: zookeeper
    restart: always
    environment:
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL: ERROR
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Djava.security.auth.login.config=/etc/zookeeper/security/zookeeper-server.jaas"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data:rw
      - zookeeper_log:/var/lib/zookeeper/log:rw
      - ./zookeeper-server.jaas:/etc/zookeeper/security/zookeeper-server.jaas:ro
    networks:
      - overlay
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}

  kafka:
    image: ${KAFKA_IMAGE}
    hostname: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_LISTENERS: "EXTERNAL://:${KAFKA_PORT},INTERNAL://:${KAFKA_PORT_EXTERNAL}"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://kafka:${KAFKA_PORT},INTERNAL://127.0.0.1:${KAFKA_PORT_EXTERNAL}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka-server.jaas"
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    volumes:
      - ./kafka-server.jaas:/etc/kafka/secrets/kafka-server.jaas:ro
      - kafka_data:/var/lib/kafka/data/:rw
    networks:
      - overlay
    ports:
      - ${KAFKA_PORT_EXTERNAL}:${KAFKA_PORT_EXTERNAL}
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local
  kafka_data:
    driver: local
networks:
  overlay:
